local gab = require("git-auto-backup")

describe("git-auto-backup config", function()
  before_each(function()
    package.loaded["git-auto-backup"] = nil
    gab = require("git-auto-backup")
  end)

  it("returns default config when setup called with empty table", function()
    gab.setup({})
    local config = gab.get_config()
    assert.equals(15, config.interval)
    assert.equals("auto-backup", config.commit_prefix)
    assert.is_true(config.push)
    assert.is_true(config.pull)
    assert.is_true(config.pull_on_open)
    assert.is_true(config.enabled)
    assert.same({}, config.dirs)
  end)

  it("merges user config with defaults", function()
    gab.setup({ interval = 30, push = false })
    local config = gab.get_config()
    assert.equals(30, config.interval)
    assert.is_false(config.push)
    assert.is_true(config.pull)
  end)

  it("expands tilde in dir paths", function()
    local home = vim.fn.expand("~")
    local tmpdir = vim.fn.tempname()
    vim.fn.mkdir(tmpdir, "p")
    vim.fn.system("git -C " .. vim.fn.shellescape(tmpdir) .. " init")
    vim.fn.system("git -C " .. vim.fn.shellescape(tmpdir) .. " config user.email 'test@test.com'")
    vim.fn.system("git -C " .. vim.fn.shellescape(tmpdir) .. " config user.name 'Test'")
    vim.fn.system("git -C " .. vim.fn.shellescape(tmpdir) .. " commit --allow-empty -m 'init'")

    local tilde_path = tmpdir:gsub("^" .. vim.pesc(home), "~")
    gab.setup({ dirs = { tilde_path } })
    local config = gab.get_config()
    assert.equals(tmpdir, config.dirs[1])
    vim.fn.delete(tmpdir, "rf")
  end)
end)
